-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 13:12:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Selection_Committee_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Selection_Committee_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Selection_Committee_database` DEFAULT CHARACTER SET utf8 ;
USE `Selection_Committee_database` ;

-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(37) CHARACTER SET 'utf8' NULL,
  `second_name` VARCHAR(37) CHARACTER SET 'utf8' NULL,
  `patronymic` VARCHAR(37) CHARACTER SET 'utf8' NULL,
  `age` INT NULL,
  `town` VARCHAR(37) CHARACTER SET 'utf8' NULL,
  `login` VARCHAR(37) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(37) CHARACTER SET 'utf8' NOT NULL,
  `Roles_role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_Users_Roles_idx` (`Roles_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Roles`
    FOREIGN KEY (`Roles_role_id`)
    REFERENCES `Selection_Committee_database`.`Roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Faculties` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `subject_1_id` INT NOT NULL,
  `subject_2_id` INT NOT NULL,
  `subject_3_id` INT NOT NULL,
  `selection_plan` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Statements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Statements` (
  `statement_id` INT NOT NULL AUTO_INCREMENT,
  `summary_points` INT NOT NULL,
  `Users_user_id` INT NOT NULL,
  `Faculties_faculty_id` INT NOT NULL,
  PRIMARY KEY (`statement_id`),
  INDEX `fk_Statements_Users1_idx` (`Users_user_id` ASC) VISIBLE,
  INDEX `fk_Statements_Faculties1_idx` (`Faculties_faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_Statements_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `Selection_Committee_database`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Statements_Faculties1`
    FOREIGN KEY (`Faculties_faculty_id`)
    REFERENCES `Selection_Committee_database`.`Faculties` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Faculty_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Faculty_subjects` (
  `Subjects_subject_id` INT NOT NULL,
  `Faculties_faculty_id` INT NOT NULL,
  PRIMARY KEY (`Subjects_subject_id`, `Faculties_faculty_id`),
  INDEX `fk_Faculty_subjects_Faculties1_idx` (`Faculties_faculty_id` ASC) VISIBLE,
  CONSTRAINT `fk_Faculty_subjects_Subjects1`
    FOREIGN KEY (`Subjects_subject_id`)
    REFERENCES `Selection_Committee_database`.`Subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faculty_subjects_Faculties1`
    FOREIGN KEY (`Faculties_faculty_id`)
    REFERENCES `Selection_Committee_database`.`Faculties` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Selection_Committee_database`.`Enrollee_Points_From_Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Selection_Committee_database`.`Enrollee_Points_From_Subject` (
  `points` INT NULL,
  `Users_user_id` INT NOT NULL,
  `Subjects_subject_id` INT NOT NULL,
  PRIMARY KEY (`Users_user_id`, `Subjects_subject_id`),
  INDEX `fk_Enrollee_Points_From_Subject_Subjects1_idx` (`Subjects_subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_Enrollee_Points_From_Subject_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `Selection_Committee_database`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enrollee_Points_From_Subject_Subjects1`
    FOREIGN KEY (`Subjects_subject_id`)
    REFERENCES `Selection_Committee_database`.`Subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
